steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vocal-coach-ai-api:$COMMIT_SHA'
      - '--build-arg'
      - 'GROQ_API_KEY=${_GROQ_API_KEY}'
      - '--build-arg'
      - 'LETTA_API_KEY=${_LETTA_API_KEY}'
      - '--build-arg'
      - 'SUPABASE_URL=${_SUPABASE_URL}'
      - '--build-arg'
      - 'SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY}'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vocal-coach-ai-api:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vocal-coach-ai-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vocal-coach-ai-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'SUPABASE_URL=${_SUPABASE_URL},SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY},ASI_1_API_KEY=${_ASI_1_API_KEY},LETTA_API_KEY=${_LETTA_API_KEY},LETTA_AGENT_ID=${_LETTA_AGENT_ID}'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/vocal-coach-ai-api:$COMMIT_SHA'

# Build timeout
timeout: '1200s' 