[build-system]
requires = ["setuptools >= 42.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vocal-coach-ai-backend"
version = "0.1.0"
description = "FastAPI backend for Vocal Coach AI application"
requires-python = ">=3.11" 